// Materializes public/robots.txt - the crawl rules this deployment publishes.
//
// Generated rather than committed because `develop` and `main` are deliberately
// kept at the same code level: the preview deploy renders the same pages as
// production from the same live editorial content, so the only thing that can
// tell a crawler the two apart is per-environment build configuration. It is
// written into public/ - Astro copies that directory to the site root verbatim,
// which is the only place a crawler looks for /robots.txt - alongside the
// generated _redirects and ads.txt, and is gitignored for the same reason.
//
// Two outputs, from PUBLIC_SITE_ENV:
//
//   production - the real rules, plus the sitemap, built from SITE_URL so the
//                sitemap line can never name a host this build does not serve.
//   preview    - the same crawl rules WITHOUT the sitemap, and a header saying
//                what this deployment is.
//
// The preview file deliberately does NOT `Disallow: /`. Keeping crawlers out of
// the index here is the `noindex` on every page (SEOHead.astro), and Google is
// explicit that a page blocked by robots.txt cannot be crawled and therefore
// cannot have its noindex seen - so a blanket disallow would *preserve* anything
// already indexed rather than remove it. Blocking discovery and blocking
// indexing are different jobs; this file does neither on its own, and says so.
//
// Run before the build (see package.json -> scripts.prebuild). Safe to re-run;
// the output is overwritten in place.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(__dirname, '../public/robots.txt');

const MARKER = '# Auto-generated by scripts/generate-robots.mjs.';

/**
 * The only value that means "this is the real site". Kept identical to
 * `PRODUCTION` in src/lib/site-env.ts, which this cannot import - it runs as
 * plain node before the build, the same constraint generate-ads-txt.mjs has with
 * publisherId(). The two must agree, or a build renders `noindex` on every page
 * while publishing a robots.txt inviting the crawler in.
 */
const PRODUCTION = 'production';

/** Paths no deployment wants crawled: the redirect hop and any API surface. */
const DISALLOWED = ['/api/', '/go/'];

const isProduction = (process.env.PUBLIC_SITE_ENV ?? '').trim() === PRODUCTION;
const siteUrl = (process.env.SITE_URL ?? 'https://sleekdrops.com').trim().replace(/\/+$/, '');

const header = isProduction
  ? []
  : [
      '# PREVIEW DEPLOYMENT - not the live site.',
      '#',
      '# Every page here also carries <meta name="robots" content="noindex, nofollow">,',
      '# and that is what keeps this build out of the index. Crawling is deliberately',
      '# not blocked: a page a crawler cannot fetch is a page whose noindex it cannot',
      '# see, which would preserve anything already indexed instead of removing it.',
      '#',
    ];

const sitemap = isProduction ? ['', `Sitemap: ${siteUrl}/sitemap-index.xml`] : [];

const contents = [
  MARKER,
  `# Source: PUBLIC_SITE_ENV=${isProduction ? PRODUCTION : 'preview'} for this build.`,
  '# Do NOT edit by hand - your changes will be overwritten on the next build.',
  ...header,
  'User-agent: *',
  'Allow: /',
  ...DISALLOWED.map((path) => `Disallow: ${path}`),
  ...sitemap,
  '',
].join('\n');

writeFileSync(TARGET, contents, 'utf8');
console.log(
  `[generate-robots] wrote public/robots.txt for ${isProduction ? PRODUCTION : 'preview'}` +
    `${isProduction ? ` (sitemap: ${siteUrl}/sitemap-index.xml)` : ' (noindex, no sitemap)'}.`,
);
