// Materializes public/ads.txt - the IAB authorized-sellers file the ad partner
// (Journey by Mediavine) reads from the site root to confirm who may sell this
// domain's inventory.
//
// The file is the partner's, not ours: Journey issues it in the dashboard
// (Settings > Ad Setup) and reissues it when its sellers change, so the source
// is a copy of that file at ads/ads.txt - or, for a partner that hosts the file
// itself, the URL in ADS_TXT_URL, fetched at build time. It is written into
// public/ - Astro copies that directory to the site root verbatim, which is the
// only place a crawler looks for /ads.txt - alongside the generated _redirects,
// and is gitignored for the same reason that one is.
//
// Production only. Outside production the file is not written at all, and any
// file a previous build left behind is removed: sleekdrops.pages.dev is not a
// domain the partner approved, and an ads.txt there authorises sellers for a
// site that does not exist. With no source configured the same happens, and an
// ads.txt authorizing nobody is worse than none, because that is the file a
// crawler reads as "this domain has revoked every seller".
//
// The content is validated before it is published - at least one
// `domain, seller id, DIRECT|RESELLER` record - and a source that fails that
// check fails the build. Every line of this file authorises somebody to sell this
// domain's inventory; a 404 page or an HTML error saved under the name would
// publish a file naming nobody, and Journey's health check would flag the site
// while the deploy read as green.
//
// Run before the build (see package.json -> scripts.prebuild). Safe to re-run;
// the output is overwritten in place.

import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(__dirname, '../ads/ads.txt');
const TARGET = resolve(__dirname, '../public/ads.txt');

const MARKER = '# Auto-generated by scripts/generate-ads-txt.mjs.';

/**
 * One authorised-seller record, per the IAB ads.txt specification: the seller's
 * domain, the publisher's account id there, and whether the relationship is
 * DIRECT or RESELLER. The optional certification-authority id after that is not
 * checked. Comment lines (`#`) and blank lines are allowed around records.
 */
const RECORD = /^[a-z0-9.-]+\.[a-z]{2,}\s*,\s*[^,\s]+\s*,\s*(DIRECT|RESELLER)\b/i;

function fail(message) {
  console.error(`\n[generate-ads-txt] ${message}\n`);
  process.exit(1);
}

/** Only ever removes a file this script wrote - never a hand-placed one. */
function removeGenerated(reason) {
  if (!existsSync(TARGET)) {
    console.log(`[generate-ads-txt] ${reason} - no ads.txt is published.`);
    return;
  }
  if (!readFileSync(TARGET, 'utf8').startsWith(MARKER)) {
    console.warn('[generate-ads-txt] public/ads.txt was not generated by this script - leaving it alone.');
    return;
  }
  rmSync(TARGET);
  console.log(`[generate-ads-txt] ${reason} - removed the generated public/ads.txt.`);
}

/** The records a candidate file carries, or an empty list for anything else. */
function records(contents) {
  return contents
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== '' && !line.startsWith('#'))
    .filter((line) => RECORD.test(line));
}

async function fetchSource(url) {
  let response;
  try {
    response = await fetch(url, { signal: AbortSignal.timeout(15_000) });
  } catch (error) {
    fail(`could not fetch ADS_TXT_URL (${url}): ${error.message}`);
  }
  if (!response.ok) fail(`ADS_TXT_URL (${url}) answered HTTP ${response.status}.`);
  return { contents: await response.text(), origin: `ADS_TXT_URL (${url})` };
}

function committedSource() {
  return { contents: readFileSync(SOURCE, 'utf8'), origin: 'ads/ads.txt' };
}

const production = (process.env.PUBLIC_SITE_ENV ?? '').trim() === 'production';
const url = (process.env.ADS_TXT_URL ?? '').trim();

if (!production) {
  removeGenerated('non-production build');
} else if (!url && !existsSync(SOURCE)) {
  removeGenerated('no ADS_TXT_URL and no ads/ads.txt');
} else {
  const { contents, origin } = url ? await fetchSource(url) : committedSource();
  const found = records(contents);
  if (found.length === 0) {
    fail(
      `${origin} carries no authorised-seller record (expected at least one ` +
        '`domain, seller id, DIRECT|RESELLER` line) - refusing to publish public/ads.txt.',
    );
  }
  const output = [
    MARKER,
    `# Source: ${origin}, issued by the ad partner. Do NOT edit by hand.`,
    '',
    contents.trim(),
    '',
  ].join('\n');
  writeFileSync(TARGET, output, 'utf8');
  console.log(`[generate-ads-txt] wrote public/ads.txt (${found.length} seller record(s)) from ${origin}.`);
}
