// Materializes public/robots.txt - the crawl rules this deployment publishes.
//
// The rules themselves live in src/lib/robots-policy.mjs, where they are
// unit-tested against the parse a crawler performs on them (a named agent group
// silently replaces the wildcard, so "GPTBot may not fetch /go/" is a property
// of the whole file rather than of any line in it). This script is the wiring:
// read the environment, write the file.
//
// Generated rather than committed because `develop` and `main` are deliberately
// kept at the same code level: the preview deploy renders the same pages as
// production from the same live editorial content, so the only thing that can
// tell a crawler the two apart is per-environment build configuration. It is
// written into public/ - Astro copies that directory to the site root verbatim,
// which is the only place a crawler looks for /robots.txt - alongside the
// generated _redirects, ads.txt and llms.txt, and is gitignored for the same
// reason.
//
// Two outputs, from PUBLIC_SITE_ENV:
//
//   production - the real rules, plus the sitemap and the llms.txt pointers,
//                built from SITE_URL so no line can name a host this build does
//                not serve.
//   preview    - the same crawl rules WITHOUT those absolute URLs, and a header
//                saying what this deployment is.
//
// The preview file deliberately does NOT `Disallow: /`. Keeping crawlers out of
// the index here is the `noindex` on every page (SEOHead.astro), and Google is
// explicit that a page blocked by robots.txt cannot be crawled and therefore
// cannot have its noindex seen - so a blanket disallow would *preserve* anything
// already indexed rather than remove it. Blocking discovery and blocking
// indexing are different jobs; this file does neither on its own, and says so.
//
// Run before the build, AFTER generate-llms-txt.mjs (see package.json ->
// scripts.prebuild): the llms.txt pointers are only written when that script
// actually produced the files. Safe to re-run; the output is overwritten in
// place.

import { existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildRobotsTxt } from '../src/lib/robots-policy.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(__dirname, '../public/robots.txt');
/** Both pointers are advertised together, so both files have to be there. */
const CONTENT_MAP = [
  resolve(__dirname, '../public/llms.txt'),
  resolve(__dirname, '../public/llms-full.txt'),
];

const MARKER = '# Auto-generated by scripts/generate-robots.mjs.';

/**
 * The only value that means "this is the real site". Kept identical to
 * `PRODUCTION` in src/lib/site-env.ts, which this cannot import - it runs as
 * plain node before the build, the same constraint generate-ads-txt.mjs has with
 * publisherId(). The two must agree, or a build renders `noindex` on every page
 * while publishing a robots.txt inviting the crawler in.
 */
const PRODUCTION = 'production';

const isProduction = (process.env.PUBLIC_SITE_ENV ?? '').trim() === PRODUCTION;
const siteUrl = (process.env.SITE_URL ?? 'https://sleekdrops.com').trim().replace(/\/+$/, '');
const hasContentMap = CONTENT_MAP.every((file) => existsSync(file));

writeFileSync(
  TARGET,
  buildRobotsTxt({
    deployment: isProduction ? PRODUCTION : 'preview',
    siteUrl,
    hasContentMap,
    marker: MARKER,
  }),
  'utf8',
);

console.log(
  `[generate-robots] wrote public/robots.txt for ${isProduction ? PRODUCTION : 'preview'}` +
    `${isProduction ? ` (sitemap: ${siteUrl}/sitemap-index.xml` : ' (noindex, no sitemap'}` +
    `${hasContentMap ? ', llms.txt advertised' : ', no llms.txt'}).`,
);
