// Materializes public/ads.txt - the IAB authorized-sellers file the ad partner
// reads from the site root to confirm this domain may sell its inventory.
//
// Generated rather than committed because the publisher id is per-environment
// build configuration (PUBLIC_ADSENSE_CLIENT, the same value src/lib/ads.ts
// loads the partner script with), so develop and production publish different
// lines from one source. It is written into public/ - Astro copies that
// directory to the site root verbatim, which is the only place a crawler looks
// for /ads.txt - alongside the generated _redirects, and is gitignored for the
// same reason that one is.
//
// With no publisher id configured the file is not written at all, and any file a
// previously configured build left behind is removed: no ads are served in that
// build either, and an ads.txt authorizing nobody is worse than none, because
// that is the file a crawler reads as "this domain has revoked every seller".
//
// Run before the build (see package.json -> scripts.prebuild). Safe to re-run;
// the output is overwritten in place.

import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(__dirname, '../public/ads.txt');

const MARKER = '# Auto-generated by scripts/generate-ads-txt.mjs.';

/**
 * Google's certification-authority id, the fourth field of every google.com
 * record. Fixed and public - it identifies Google as the seller, not this site.
 */
const GOOGLE_TAG_ID = 'f08c47fec0942fa0';

/** Only ever removes a file this script wrote - never a hand-placed one. */
function removeGenerated() {
  if (!existsSync(TARGET)) return;
  if (!readFileSync(TARGET, 'utf8').startsWith(MARKER)) {
    console.warn('[generate-ads-txt] public/ads.txt was not generated by this script - leaving it alone.');
    return;
  }
  rmSync(TARGET);
  console.log('[generate-ads-txt] no PUBLIC_ADSENSE_CLIENT - removed the generated public/ads.txt.');
}

const client = (process.env.PUBLIC_ADSENSE_CLIENT ?? '').trim();

if (!client) {
  removeGenerated();
} else {
  // ads.txt names the publisher WITHOUT the `ca-` prefix the ad tag carries:
  // `ca-pub-123` in PUBLIC_ADSENSE_CLIENT is seller `pub-123` here. Passing the
  // tag form through verbatim yields a record Google cannot match, which reads
  // to the crawler as an unauthorized domain.
  const seller = client.replace(/^ca-/, '');
  const contents = [
    MARKER,
    '# Source: PUBLIC_ADSENSE_CLIENT for this build.',
    '# Do NOT edit by hand - your changes will be overwritten on the next build.',
    `google.com, ${seller}, DIRECT, ${GOOGLE_TAG_ID}`,
    '',
  ].join('\n');
  writeFileSync(TARGET, contents, 'utf8');
  console.log(`[generate-ads-txt] wrote public/ads.txt for ${seller}.`);
}
