/**
 * /llms.txt and /llms-full.txt, built from a fixture content collection written
 * to disk in exactly the form `scripts/fetch-content.mjs` writes - one
 * `key: <JSON>` frontmatter line per field, a GFM body with `##`/`###`
 * headings, a comparison table and `/go/` links - because that is the only
 * input the generator ever gets.
 *
 * Three things here are contracts rather than formatting:
 *   - a draft or future-dated post is not published, so it is not mapped;
 *   - a thin page never reaches the curated file;
 *   - no `/go/` affiliate redirect appears in either file, whatever an article
 *     body links to. robots.txt disallows that path to every crawler, and these
 *     files must not be the back door around it.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { categories } from '../data/categories.ts';
import { SITE_DESCRIPTION, SITE_NAME } from '../data/site.ts';
import {
  MIN_CURATED_WORDS,
  STRENGTH_WEIGHTS,
  buildLlmsFullTxt,
  buildLlmsTxt,
  curate,
  plainText,
  readArticleIndex,
  scoreArticle,
  strengthSignals,
  toArticleRecord,
} from './llms-txt.mjs';

const SITE = 'https://sleekdrops.com';
const MARKER = 'Generated by scripts/generate-llms-txt.mjs';
const NOW = new Date('2026-09-09T00:00:00Z');

/** Bulk prose with no figures in it, so each fixture's word count is deliberate. */
const FILLER = 'the rest of this section works through the trade offs in plain prose'.split(' ');
const filler = (words: number): string =>
  Array.from({ length: words }, (_, i) => FILLER[i % FILLER.length]).join(' ');

interface Fixture {
  slug: string;
  frontmatter: Record<string, unknown>;
  body: string;
}

const VACUUMS: Fixture = {
  slug: 'best-cordless-stick-vacuums',
  frontmatter: {
    title: 'Best cordless stick vacuums in Australia (2026)',
    dek: 'Six sticks compared, and the one that beats a Dyson on hard floors.',
    category: 'Home',
    postType: 'roundup',
    author: 'mira',
    tags: ['Cordless vacuums', 'Australia'],
    pubDate: '2026-08-30',
    updatedDate: '2026-09-04',
    readTime: 9,
    cover: 'fill-2',
    featured: true,
    draft: false,
  },
  body: `Buy the [Shark Detect Pro](/go/shark-detect-pro) if you have hard floors and a dog. It holds suction at the head for 38 minutes, lands at $499 RRP (Shark, 2026 price list) against the $1,099 of the Dyson V15 (Dyson, 2026 RRP), and empties without your hand near the dust.

| Model | RRP (2026) | Runtime | Where |
| --- | --- | --- | --- |
| Shark Detect Pro | $499 | 38 minutes | [Shark](/go/shark-detect-pro) |
| Dyson V15 Detect | $1,099 | 60 minutes | [Dyson](/go/dyson-v15-detect) |

## How we picked

We read 1,400 owner reviews on ProductReview.com.au (2026) and the teardown notes Choice published (Choice, 2026). ${filler(200)}

## What breaks after a year

Filter clogging at about 14 months is the complaint that repeats (ProductReview.com.au, 2026), and it costs $39 to fix. ${filler(200)}

## Who should not buy one

${filler(200)}

## FAQ

### How long do cordless vacuum batteries last?

Three to five years of daily use before runtime drops noticeably (Shark, 2026 support notes). ${filler(60)}

### Is the Dyson V15 worth $600 more?

Only on deep carpet, where its runtime advantage of 22 minutes matters. ${filler(60)}

### Can a stick vacuum replace a barrel vacuum?

${filler(60)}

### What does a replacement filter cost in Australia?

About $39 for the Shark and $79 for the Dyson (2026 RRP). ${filler(60)}
`,
};

const SPEAKERS: Fixture = {
  slug: 'best-portable-waterproof-bluetooth-speakers',
  frontmatter: {
    title: 'Best portable waterproof Bluetooth speakers',
    dek: 'Five speakers rated for the pool, the beach and the shower.',
    category: 'Tech',
    postType: 'roundup',
    author: 'theo',
    tags: ['Bluetooth speakers'],
    pubDate: '2026-06-21',
    readTime: 8,
    cover: 'fill-1',
    featured: false,
    draft: false,
  },
  body: `The [JBL Flip 7](/go/jbl-flip-7) is the one to buy for most people, and the reason is prosaic rather than sonic. ${filler(60)}

## How we picked

${filler(300)}

## FAQ

### Does IP67 mean a speaker can be submerged?

${filler(60)}
`,
};

const CLOCKS: Fixture = {
  slug: 'best-sunrise-alarm-clocks',
  frontmatter: {
    title: 'Best sunrise alarm clocks for dark Melbourne mornings',
    dek: 'Wake-up lights that actually reach 300 lux before the alarm.',
    category: 'Home',
    postType: 'guide',
    author: 'mira',
    tags: ['Sleep'],
    pubDate: '2026-07-02',
    readTime: 7,
    cover: 'fill-3',
    featured: false,
    draft: false,
  },
  body: `Start with the Philips SmartSleep HF3520 at $199 RRP (Philips, 2026). ${filler(500)}

## How we picked

${filler(200)}
`,
};

/** The AdSense reviewer's example of a thin page: long enough to publish, not to map. */
const TALLOW: Fixture = {
  slug: 'beef-tallow-skincare',
  frontmatter: {
    title: 'Beef tallow skincare, explained',
    dek: 'What tallow balm does, and who it suits.',
    category: 'Health',
    postType: 'article',
    author: 'aiko',
    tags: ['Skincare'],
    pubDate: '2026-05-11',
    readTime: 4,
    cover: 'fill-4',
    featured: false,
    draft: false,
  },
  body: `Tallow balm is rendered beef fat, and it suits dry skin better than oily skin. ${filler(120)}
`,
};

const DRAFT: Fixture = {
  slug: 'unfinished-air-fryer-roundup',
  frontmatter: { ...VACUUMS.frontmatter, title: 'Unfinished air fryer roundup', draft: true },
  body: VACUUMS.body,
};

const SCHEDULED: Fixture = {
  slug: 'tomorrows-mattress-guide',
  frontmatter: {
    ...VACUUMS.frontmatter,
    title: "Tomorrow's mattress guide",
    pubDate: '2026-09-10',
    updatedDate: undefined,
    draft: false,
  },
  body: VACUUMS.body,
};

/** A fixture written exactly as fetch-content.mjs writes a post. */
function writeFixture(dir: string, fixture: Fixture): void {
  const lines = ['---'];
  for (const [key, value] of Object.entries(fixture.frontmatter)) {
    if (value === undefined) continue;
    lines.push(`${key}: ${JSON.stringify(value)}`);
  }
  lines.push('---');
  writeFileSync(join(dir, `${fixture.slug}.md`), `${lines.join('\n')}\n\n${fixture.body.trim()}\n`, 'utf8');
}

const collection = mkdtempSync(join(tmpdir(), 'llms-txt-fixture-'));
for (const fixture of [VACUUMS, SPEAKERS, CLOCKS, TALLOW, DRAFT, SCHEDULED]) {
  writeFixture(collection, fixture);
}
const articles = readArticleIndex(collection, NOW);
process.on('exit', () => rmSync(collection, { recursive: true, force: true }));

const input = {
  siteName: SITE_NAME,
  siteUrl: SITE,
  description: SITE_DESCRIPTION,
  categories,
  articles,
  deployment: 'production' as const,
  generatedAt: NOW,
  marker: MARKER,
};

const llms = buildLlmsTxt(input);
const llmsFull = buildLlmsFullTxt(input);

test('the fixture collection reduces to the four published articles, strongest first', () => {
  assert.deepEqual(
    articles.map((a) => a.slug),
    [VACUUMS.slug, CLOCKS.slug, SPEAKERS.slug, TALLOW.slug],
  );
});

test('a draft and a future-dated post are not mapped for a crawler', () => {
  for (const file of [llms, llmsFull]) {
    assert.ok(!file.includes(DRAFT.slug), 'a draft leaked into a published map');
    assert.ok(!file.includes(SCHEDULED.slug), 'a scheduled post leaked into a published map');
  }
});

test('llms.txt opens with the site name, the site description and its provenance', () => {
  assert.ok(llms.startsWith(`# ${SITE_NAME}\n`));
  assert.ok(llms.includes(`> ${SITE_DESCRIPTION}`));
  assert.ok(llms.includes(`${MARKER} on 2026-09-09 from 4 published articles. Do not edit by hand.`));
  assert.ok(llms.includes(`${SITE}/llms-full.txt`), 'the fuller file is linked from the short one');
  assert.ok(
    llms.includes('The sections below hold the strongest articles in each category rather than every'),
    'the file must not read as a claim to list everything the categories count',
  );
  assert.ok(llms.includes(`${SITE}/sitemap-index.xml`));
  assert.ok(llms.endsWith('\n'));
});

test('llms.txt lists only the categories that have articles, with their counts', () => {
  assert.ok(llms.includes(`- [Home](${SITE}/category/home): Kitchens, desks, the long, quiet half of the house. 2 articles.`));
  assert.ok(llms.includes(`- [Tech](${SITE}/category/tech):`));
  assert.ok(llms.includes(`- [Health](${SITE}/category/health):`));
  assert.ok(llms.includes('1 article.'), 'a single article is not "1 articles"');
  for (const empty of ['Fashion', 'Finance', 'Travel']) {
    assert.ok(!llms.includes(`/category/${empty.toLowerCase()}`), `${empty} has nothing to send an agent to`);
  }
});

test('the curated list carries each article once, under its category, with its dek', () => {
  assert.ok(
    llms.includes(
      `## Home\n\n- [${VACUUMS.frontmatter.title}](${SITE}/blog/${VACUUMS.slug}): ${VACUUMS.frontmatter.dek}\n` +
        `- [${CLOCKS.frontmatter.title}](${SITE}/blog/${CLOCKS.slug}): ${CLOCKS.frontmatter.dek}`,
    ),
    llms,
  );
  assert.ok(llms.includes(`## Tech\n\n- [${SPEAKERS.frontmatter.title}](${SITE}/blog/${SPEAKERS.slug}):`));
});

test('a page too thin to be worth a fetch is left out of the curated file, not the full one', () => {
  const tallow = articles.find((a) => a.slug === TALLOW.slug)!;
  assert.ok(tallow.wordCount < MIN_CURATED_WORDS, 'the fixture is meant to be a stub');
  assert.ok(!llms.includes(TALLOW.slug), 'a stub was offered as one of the site\'s strongest pages');
  assert.ok(!llms.includes('## Health'), 'and its category has nothing else to list');
  assert.ok(llmsFull.includes(`## ${TALLOW.frontmatter.title}`), 'llms-full.txt is the whole corpus');
});

test('no affiliate redirect reaches either file, even from a lead paragraph', () => {
  const vacuums = articles.find((a) => a.slug === VACUUMS.slug)!;
  assert.ok(vacuums.lead.includes('Shark Detect Pro'), 'the link label survives');
  assert.ok(!vacuums.lead.includes('/go/'), 'the link target does not');
  for (const [name, file] of [
    ['llms.txt', llms],
    ['llms-full.txt', llmsFull],
  ] as const) {
    assert.ok(!file.includes('/go/'), `${name} hands a crawler the affiliate hop robots.txt disallows`);
  }
});

test('llms.txt closes with the trust pages, in a section an agent will not skip', () => {
  assert.ok(!llms.includes('## Optional'), '`## Optional` is the section the convention says may be dropped');
  const about = llms.slice(llms.indexOf('## About this site'));
  for (const path of ['/about', '/disclaimer', '/privacy', '/rss.xml']) {
    assert.ok(about.includes(`${SITE}${path}`), `${path} is missing from the trust section`);
  }
});

test('llms-full.txt carries the facts, the lead, the sections and the FAQ pairs', () => {
  const entry = llmsFull.slice(llmsFull.indexOf(`## ${VACUUMS.frontmatter.title}`));
  assert.ok(entry.includes(`- URL: ${SITE}/blog/${VACUUMS.slug}`));
  assert.ok(entry.includes('- Category: Home'));
  assert.ok(entry.includes('- Type: roundup'));
  assert.ok(entry.includes('- Published: 2026-08-30'));
  assert.ok(entry.includes('- Updated: 2026-09-04'), 'freshness is the signal an engine weights');
  assert.match(entry, /- Length: \d+ words, 9 min read/);
  assert.ok(entry.includes('- Tags: Cordless vacuums, Australia'));
  assert.ok(entry.includes(`Summary: ${VACUUMS.frontmatter.dek}`));
  assert.ok(entry.includes('Opens by answering: Buy the Shark Detect Pro if you have hard floors'));
  assert.ok(
    entry.includes('Covers: How we picked; What breaks after a year; Who should not buy one.'),
    'the H2s, without the FAQ wrapper heading',
  );
  assert.ok(entry.includes('Answers outright:\n- How long do cordless vacuum batteries last?'));
  assert.ok(entry.includes('- What does a replacement filter cost in Australia?'));
});

test('an article with no update date says so by omission rather than by inventing one', () => {
  const entry = llmsFull.slice(llmsFull.indexOf(`## ${SPEAKERS.frontmatter.title}`));
  const facts = entry.slice(0, entry.indexOf('Summary:'));
  assert.ok(facts.includes('- Published: 2026-06-21'));
  assert.ok(!facts.includes('- Updated:'), 'a post never re-checked must not claim an update date');
});

test('a preview build says what it is, and still points at the canonical site', () => {
  const previewFile = buildLlmsTxt({ ...input, deployment: 'preview' });
  assert.match(previewFile, /^PREVIEW DEPLOYMENT - not the live site\./m);
  assert.ok(previewFile.includes(`${SITE}/blog/${VACUUMS.slug}`));
});

test('a trailing slash on SITE_URL never doubles up in an emitted URL', () => {
  for (const file of [buildLlmsTxt({ ...input, siteUrl: `${SITE}/` }), buildLlmsFullTxt({ ...input, siteUrl: `${SITE}/` })]) {
    assert.ok(!file.includes('sleekdrops.com//'));
  }
});

test('an empty collection builds a file with no articles rather than throwing', () => {
  // The generator removes the files in this case; the builder must still be safe,
  // because a collection of nothing but drafts reaches it the same way.
  const empty = { ...input, articles: [] };
  assert.ok(buildLlmsTxt(empty).includes('from 0 published articles'));
  assert.ok(!buildLlmsTxt(empty).includes('## Categories'));
  assert.ok(buildLlmsFullTxt(empty).endsWith('\n'));
});

test('strength rewards evidence and figures over length alone', () => {
  const base = {
    title: 'A',
    dek: 'A',
    category: 'Tech',
    postType: 'guide',
    author: 'theo',
    pubDate: '2026-09-01',
    tags: [],
  };
  const record = (body: string, extra: Record<string, unknown> = {}) =>
    toArticleRecord('a', { ...base, ...extra }, body, NOW);

  const padded = record(`## One\n\n${filler(1600)}`);
  const evidenced = record(
    `## One\n\n${filler(1400)} The Shark holds 38 minutes of runtime at $499 RRP (Shark, 2026 price list), against 60 minutes at $1,099 (Dyson, 2026 RRP).`,
  );
  assert.ok(scoreArticle(evidenced, NOW) > scoreArticle(padded, NOW), 'dated, checkable claims must count for more');

  const stale = record(`## One\n\n${filler(1600)}`, { pubDate: '2024-01-01' });
  assert.ok(scoreArticle(padded, NOW) > scoreArticle(stale, NOW), 'freshness is a ranking signal for engines');

  const maintained = record(`## One\n\n${filler(1600)}`, { updatedDate: '2026-09-08' });
  assert.ok(scoreArticle(maintained, NOW) > scoreArticle(padded, NOW), 'a re-checked page is a stronger citation');
});

test('every weighted signal is one the scorer computes, and stays inside 0-1', () => {
  // A weight with no signal, or a signal with no weight, would turn every score
  // into NaN and leave the ranking in file order without failing anything.
  const strongest = articles[0];
  const signals = strengthSignals(strongest, NOW);
  assert.deepEqual(Object.keys(signals).sort(), Object.keys(STRENGTH_WEIGHTS).sort());
  for (const [signal, value] of Object.entries(signals)) {
    assert.ok(value >= 0 && value <= 1, `${signal} is ${value}, outside 0-1`);
  }
  assert.ok(Number.isFinite(strongest.score) && strongest.score > 0);
  const ceiling = Object.values(STRENGTH_WEIGHTS).reduce((sum, weight) => sum + weight, 0);
  assert.ok(strongest.score <= ceiling);
});

test('no single category is allowed to fill the curated file', () => {
  const capped = curate(articles, { perCategory: 1 });
  assert.deepEqual(
    capped.map((a) => a.slug),
    [VACUUMS.slug, SPEAKERS.slug],
    'one Home article, one Tech article, and the stub still excluded',
  );
  assert.equal(curate(articles, { limit: 2 }).length, 2);
});

test('both files carry the marker the generator deletes them by', () => {
  // generate-llms-txt.mjs removes a stale file only when it finds this string in
  // it, so the two drifting apart would leave a stale map published forever.
  const script = readFileSync(
    fileURLToPath(new URL('../../scripts/generate-llms-txt.mjs', import.meta.url)),
    'utf8',
  );
  const declared = /^const MARKER = '(.+)';$/m.exec(script);
  assert.ok(declared, 'generate-llms-txt.mjs no longer declares a MARKER');
  assert.equal(declared[1], MARKER);
  for (const build of [buildLlmsTxt, buildLlmsFullTxt]) {
    assert.ok(build({ ...input, marker: declared[1] }).includes(declared[1]));
  }
});

test('plainText keeps prose and drops everything a crawler should not read', () => {
  assert.equal(plainText('**Bold** and [a link](/go/slug) and `code`'), 'Bold and a link and code');
  assert.equal(plainText('![alt](https://img.example/x.png) after'), 'after');
  assert.equal(plainText('a <span class="x">tag</span> b'), 'a tag b');
  // A table's cells are prose; its pipes and alignment row are not words.
  assert.equal(
    plainText('| Model | RRP |\n| --- | --- |\n| Shark | $499 |'),
    'Model RRP Shark $499',
  );
});

test('a future update date cannot score above a page checked today', () => {
  // A scheduled re-publish would otherwise push the recency signal past 1 and
  // rank a post the site has not touched yet above everything else.
  const base = { title: 'A', dek: 'A', category: 'Tech', pubDate: '2026-09-01', tags: [] };
  const body = `## One\n\n${filler(1600)}`;
  const scheduled = toArticleRecord('a', { ...base, updatedDate: '2027-06-01' }, body, NOW);
  const today = toArticleRecord('b', { ...base, updatedDate: '2026-09-09' }, body, NOW);
  assert.equal(strengthSignals(scheduled, NOW).recency, 1);
  assert.equal(scoreArticle(scheduled, NOW), scoreArticle(today, NOW));
});
