/**
 * The crawl policy, asserted the way a crawler reads it: parse the whole
 * emitted file, resolve the group that names the agent, then ask whether a path
 * is fetchable.
 *
 * Asserting the arrays the file was built from would prove nothing here. Under
 * RFC 9309 a crawler that finds its own token obeys that group and ignores
 * `User-agent: *` entirely, so naming GPTBot at all takes it *out* of the
 * wildcard's `Disallow: /go/` - and a blank line in the wrong place, or a
 * forgotten Disallow, opens the affiliate redirect to exactly the agents this
 * file was written to be explicit with. That is a property of the text as a
 * whole, so the text as a whole is what is tested.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import {
  AI_AGENT_GROUPS,
  AI_AGENT_TOKENS,
  DISALLOWED_PATHS,
  buildRobotsTxt,
  isAllowed,
  matchRules,
} from './robots-policy.mjs';

const SITE = 'https://sleekdrops.com';
const MARKER = '# Auto-generated by scripts/generate-robots.mjs.';

const production = buildRobotsTxt({
  deployment: 'production',
  siteUrl: SITE,
  hasContentMap: true,
  marker: MARKER,
});
const preview = buildRobotsTxt({ deployment: 'preview', siteUrl: SITE, hasContentMap: true, marker: MARKER });

/** Paths that stand in for the three things a crawler can reach on this site. */
const ARTICLE = '/blog/best-cordless-stick-vacuums';
const REDIRECT = '/go/shark-detect-pro';
const API = '/api/feedback';

test('the wildcard group still says exactly what it said before', () => {
  // Everything below adds groups; this is the one that must not change, because
  // every crawler that is not named by the new blocks still reads it.
  for (const robots of [production, preview]) {
    assert.match(robots, /^User-agent: \*\nAllow: \/\nDisallow: \/api\/\nDisallow: \/go\/$/m);
    assert.equal(matchRules(robots, 'Googlebot').token, '*');
    assert.equal(isAllowed(robots, 'Googlebot', ARTICLE), true);
    assert.equal(isAllowed(robots, 'Googlebot', REDIRECT), false);
    assert.equal(isAllowed(robots, 'Googlebot', API), false);
  }
});

test('/go/ and /api/ stay disallowed for every named AI agent, on both deployments', () => {
  assert.deepEqual(DISALLOWED_PATHS, ['/api/', '/go/']);
  assert.ok(AI_AGENT_TOKENS.length >= 15, 'the point of the block is naming the majors');

  for (const [label, robots] of [
    ['production', production],
    ['preview', preview],
  ] as const) {
    for (const agent of AI_AGENT_TOKENS) {
      const matched = matchRules(robots, agent);
      assert.equal(matched.token, agent.toLowerCase(), `${agent} (${label}) is not named by its own group`);
      assert.equal(isAllowed(robots, agent, REDIRECT), false, `${agent} (${label}) may fetch the affiliate redirect`);
      assert.equal(isAllowed(robots, agent, API), false, `${agent} (${label}) may fetch the API surface`);
      assert.equal(isAllowed(robots, agent, ARTICLE), true, `${agent} (${label}) may not read the articles`);
    }
  }
});

test('agent tokens match case-insensitively, as the spec requires', () => {
  assert.equal(isAllowed(production, 'gptbot', REDIRECT), false);
  assert.equal(isAllowed(production, 'CLAUDEBOT', REDIRECT), false);
  assert.equal(isAllowed(production, 'gptbot', ARTICLE), true);
});

test('every named token appears once, spelled as its operator sends it', () => {
  assert.deepEqual([...new Set(AI_AGENT_TOKENS)], AI_AGENT_TOKENS, 'a token listed twice would split its group');
  for (const token of AI_AGENT_TOKENS) {
    assert.match(token, /^[A-Za-z][A-Za-z0-9-]*$/, `${token} is not a robots.txt product token`);
    assert.match(production, new RegExp(`^User-agent: ${token}$`, 'm'));
  }
  // The operators are what make the block auditable rather than a token dump.
  for (const { operator, tokens } of AI_AGENT_GROUPS) {
    assert.ok(tokens.length > 0, `${operator} names no agent`);
    assert.match(production, new RegExp(`^# ${operator.replace(/[()]/g, '\\$&')}$`, 'm'));
  }
});

test('the search crawlers are left to the wildcard rather than duplicated', () => {
  // Two places holding the same rules is how they drift apart.
  for (const searchBot of ['Googlebot', 'Bingbot', 'Applebot', 'DuckDuckBot']) {
    assert.equal(matchRules(production, searchBot).token, '*', `${searchBot} should not have its own group`);
  }
  // The Gemini and Apple Intelligence opt-in tokens are not crawlers, and are
  // the two entries that would be pointless to leave to the wildcard.
  assert.ok(AI_AGENT_TOKENS.includes('Google-Extended'));
  assert.ok(AI_AGENT_TOKENS.includes('Applebot-Extended'));
});

test('production advertises the sitemap and the content map; a preview advertises neither', () => {
  assert.match(production, /^Sitemap: https:\/\/sleekdrops\.com\/sitemap-index\.xml$/m);
  assert.ok(production.includes(`${SITE}/llms.txt`));
  assert.ok(production.includes(`${SITE}/llms-full.txt`));

  assert.ok(!/^Sitemap:/m.test(preview), 'a preview must not name a sitemap it does not serve');
  assert.ok(!preview.includes('/llms.txt'), 'nor an absolute URL on a host it does not serve');
  assert.match(preview, /# PREVIEW DEPLOYMENT - not the live site\./);
});

test('a build that wrote no llms.txt does not point an agent at one', () => {
  const robots = buildRobotsTxt({ deployment: 'production', siteUrl: SITE, marker: MARKER });
  assert.ok(!robots.includes('/llms.txt'));
  assert.match(robots, /^Sitemap:/m, 'the sitemap is unaffected');
  assert.equal(isAllowed(robots, 'GPTBot', REDIRECT), false, 'and the policy is unchanged');
});

test('a trailing slash on SITE_URL never doubles up in an emitted URL', () => {
  const robots = buildRobotsTxt({
    deployment: 'production',
    siteUrl: 'https://sleekdrops.com/',
    hasContentMap: true,
    marker: MARKER,
  });
  assert.ok(!robots.includes('sleekdrops.com//'));
});

test('the marker is the first line, so the file identifies its generator', () => {
  assert.ok(production.startsWith(`${MARKER}\n`));
  assert.ok(production.endsWith('\n'));
});

test('an agent this file has never heard of falls through to the wildcard', () => {
  assert.equal(matchRules(production, 'SomeNewAnswerEngine/1.0').token, '*');
  assert.equal(isAllowed(production, 'SomeNewAnswerEngine/1.0', REDIRECT), false);
  assert.equal(isAllowed(production, 'SomeNewAnswerEngine/1.0', ARTICLE), true);
});

test('the prebuild writes llms.txt before robots.txt, or the pointer lies', () => {
  // `hasContentMap` is read off the filesystem, so the order of these two steps
  // is what decides whether robots.txt can advertise a file that exists.
  const pkg = readFileSync(fileURLToPath(new URL('../../package.json', import.meta.url)), 'utf8');
  const { prebuild } = JSON.parse(pkg).scripts as Record<string, string>;
  const llms = prebuild.indexOf('generate-llms-txt.mjs');
  const robots = prebuild.indexOf('generate-robots.mjs');
  assert.ok(llms > -1, 'prebuild no longer generates llms.txt');
  assert.ok(robots > -1, 'prebuild no longer generates robots.txt');
  assert.ok(llms < robots, 'generate-llms-txt.mjs must run before generate-robots.mjs');
});
